source 'https://cdn.cocoapods.org/'
source 'https://github.com/volcengine/volcengine-specs.git'

# RTC SDK
pod 'BytePlusRTC', :path => './BytePlusRTC'

target 'veRTC_Demo' do
  platform :ios, '12.0'
  # 依赖 SDK
  # Depends on SDK
  pod 'Masonry'
  pod 'YYModel'
  pod 'AFNetworking', '~> 4.0'
  
  # 基础组件
  # Basic components
  pod 'Core', :path => 'Core'

  # 场景化源码
  # Scene source code
  # 登录
  # Login
  pod 'Login', :path => 'APP/Login'

  # 视频互动
  # Interactive Video streaming
  pod 'VideoChatDemo', :path => 'APP/VideoChatDemo'

end



