source 'https://cdn.cocoapods.org/'
source 'https://github.com/byteplus-sdk/byteplus-specs.git'
# RTC SDK
pod 'BytePlusRTC', '3.46.111'

target 'veRTC_Demo' do
  # Depends on SDK
  pod 'Masonry'
  pod 'YYModel'
  pod 'AFNetworking', '~> 4.0'
  
  # Basic components
  pod 'Core', :path => 'Core'
  
  # Scene source code
  # Login
  pod 'Login', :path => 'APP/Login'

  # RTS login information
  pod 'JoinRTSParams', :path => 'APP/JoinRTSParams'
  
  # Interactive Video streaming
  pod 'VideoChatDemo', :path => 'APP/VideoChatDemo'
  
end