source 'https://cdn.cocoapods.org/'
source 'https://github.com/byteplus-sdk/byteplus-specs.git'


# RTC SDK
pod 'BytePlusRTC', '3.45.612'

target 'veRTC_Demo' do
  platform :ios, '12.0'
  # Depends on SDK
  pod 'Masonry'
  pod 'YYModel'
  pod 'AFNetworking', '~> 4.0'
  
  # Basic components
  pod 'Core', :path => 'Core'
  
  # Scene source code
  # Login
  pod 'Login', :path => 'APP/Login'
  
  # RTS login information
  pod 'JoinRTSParams', :path => 'APP/JoinRTSParams'


  
  # Interactive Video streaming
  pod 'VideoChatDemo', :path => 'APP/VideoChatDemo'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      if config.name == "Enterprise"
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'ENTERPRISE=1',
        ]
      end
    end
  end
end



