source 'https://cdn.cocoapods.org/'
source 'https://github.com/byteplus-sdk/byteplus-specs.git'

# RTC SDK
pod 'BytePlusRTC', '3.50.311'

target 'RTCSolution' do
  platform :ios, '12.0'
  
  # Depends on SDK
  pod 'Masonry'
  pod 'YYModel'
  pod 'AFNetworking', '~> 4.0'
  
  # Basic Component
  pod 'ToolKit', :path => '../RTCSolution/APP/ToolKit'
  
  # Scene source code
  # Login Kit
  pod 'BytePlusLoginKit', :path => '../RTCSolution/APP/BytePlusLoginKit'

  # Get RTS Params Kit
  pod 'JoinRTSParamsKit', :path => '../RTCSolution/APP/JoinRTSParamsKit'

  # Video Chat Demo
  pod 'VideoChatDemo', :path => '../RTCSolution/APP/VideoChatDemo'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        
        config.build_settings['CODE_SIGN_IDENTITY'] = ''
        
      end
    end
  end
end
