/*
 * Copyright 2022 BytePlus Pte. Ltd.
 * SPDX-License-Identifier: MIT
 */

#ifndef BuildConfig_h
#define BuildConfig_h

/*
 You can fill in the provided server domain name for testing. However, you need
 to deploy your own server and replace this address with your own domain name,
 when officially launching this function.
 */
#define LoginUrl @""

/*
 Required for BytePlus RTC
 The unique identifier of each application. You can obtain APPID on the console.
 The instances generated by different AppIDs are completely independent  and
 cannot communicate with each other. https://console.byteplus.com/rtc/listRTC
 */
#define APPID @""

/*
 Required for BytePlus RTC
 AppKey is used to generate rtc tokens and authentication tokens.
 https://console.byteplus.com/rtc/listRTC
 */
#define APPKey @""

/*
 Required for RTS
 AccessKeyID is used for authentication when calling RTS OpenAPI at server level
 to confirm the ownership of the APPID.
 https://console.byteplus.com/iam/keymanage
 */
#define AccessKeyID @""

/*
 Required for RTS
 SecretAccessKey is used for authentication when calling RTS OpenAPI at server
 level to confirm the ownership of the APPID.
 https://console.byteplus.com/iam/keymanage
 */
#define SecretAccessKey @""

#endif /* BuildConfig_h */
